### ISSUE TITLE
The issue after merging 3dtiles

### ISSUE THREAD

**Issue by KiktMa** [CesiumGS/3d-tiles-tools#91] opened 2024-01-22 02:00 UTC
Hello, I would like to ask how to solve the problem of merging two 3DTiles data and loading them in Cesium. However, there is clearly a gap in the merged 3DTiles. Have you ever encountered this problem?
![image](https://github.com/CesiumGS/3d-tiles-tools/assets/92163667/c3c64551-4c05-49f5-9aa8-bf603bc5348d)
```bash
npx 3d-tiles-tools merge -i C:\Users\xxj\Desktop\newobj\obj\test_obj1\tileset.json -i C:\Users\xxj\Desktop\newobj\obj\test_obj2\tileset.json -o C:\Users\xxj\Desktop\newobj\obj\3dtiles
```
I use this command to merge

**Comment by javagl** [comment] 2024-01-22 02:30
The `merge` command of the tools does not affect or modify the input tilesets. It only generates a _new_ tileset that _refers_ to the input. When there is a difference (gap) in the input tilesets, it will be visible in the merged tileset. Depending on the nature and structure of the input tilesets, there _might_ be workarounds for that. But very likely, no trivial (or even "simple") ones....

**Comment by javagl** [comment] 2024-02-04 16:47
Considering that the `merge` command does not affect or depend on the geometry of the input tilesets, it is safe to say that the gap is caused by the input. 

You could try to adjust the tileset locations (i.e the root node transforms) either in the inputs, or in the merged tileset. But for the tools, there is not really any actionable item here, so I assume that it is OK to close this.

**Closed by javagl** 2024-02-04 16:47 UTC
