### ISSUE TITLE
How I can convert lot of b3dm to one gltf/glb file?

### ISSUE THREAD

**Issue by arslc** [CesiumGS/3d-tiles-tools#46] opened 2023-06-12 04:51 UTC
Hello everyone! 

I have this structure:
```bash
Model/
├─ tileset.json
├─ Data/
│  ├─ a.b3dm
│  ├─ b0.b3dm
│  ├─ b1.b3dm
│  ├─ ... and other 620 .b3dm files
```

I tried to convert it, but I can only do it one file at a time (using `3d-tiles-tools b3dmToGlb`). But unfortunately it will be very long and laborious, because I have 20 such folders, in which there are 500-1000 such tiles that need to be converted. And even if I suddenly do it manually, then I don’t understand how then I can correctly combine all these glbs into one model.

I also tried `3d-tiles-tools merge` and `3d-tiles-tools combine`, but it does not lead to anything, it just creates an output folder that contains exactly the same set of files, but tileset.json changes to this:

```json
{
   "asset": {
     "version": "1.1"
   },
   "geometricError": 10000,
   root: {
     "boundingVolume": {
       "sphere": [
         13.637106371665038,
         33.194847012305296,
         15.729257822775878,
         63.32171125738676
       ]
     },
     "refine": "ADD",
     "geometricError": 10000,
     "children": [
       {
         "boundingVolume": {
           "sphere": [
             13.637106371665038,
             33.194847012305296,
             15.729257822775878,
             63.32171125738676
           ]
         },
         "content": {
           "uri": "Model/tileset.json"
         },
         "geometricError": 4.56985088,
         "refine": "REPLACE"
       }
     ]
   }
}
```

What am I doing wrong? Can someone suggest me what needs to be done?

**Comment by vkitor** [comment] 2023-06-15 07:16
HI,

I tried to run the pipeline with  your example pipeline.json (with my input and output paths), but after b3dmtoGlb conversion finished, in output folder, there was only .b3dm files, and in .json there were also paths to .b3dm files, not .Glb files.
Do you maybe know how to fix that issue?

Thank you

**Comment by vkitor** [comment] 2023-06-15 13:53
@lilleyse  I'm using the latest version from github.

**Comment by vkitor** [comment] 2023-06-16 08:45
@lilleyse Unfortunately it was not fixed with #42.

**Comment by javagl** [comment] 2023-06-16 13:43
@vkitor To be clear: #42 is not yet part of a release. (We should schedule a release that integrates this fix soon, but for now, it would only work if you started it in a clone of the current `main` state of the repository).

If that still doesn't work for you:  Are there any error messages printed during the execution? (As part of https://github.com/CesiumGS/3d-tiles-tools/issues/31 , we'll certainly have to improve the logging, and add further log details as soon as we have a mechanism for controlling the log output), but maybe there's a hint of what is wrong.

**Comment by vkitor** [comment] 2023-06-29 10:46
Today I pulled the latest release from Github, and the problem is still there.
I got no error messages during execution, but after pipeline conversion, the format is still b3dm.

I run the command:

`$ npx 3d-tiles-tools pipeline -i /media/pip/6TB_1/data/old/3d/z.json `


my z.json file:
```
{
  "input": "/media/pip/6TB_1/data/old/3d/Draco_compressed/si_old/",
  "output": "/media/pip/6TB_1/data/old/3d/pipeline_results/",
  "tilesetStages": [
    {
      "name": "upgrade",
      "description": "Upgrade the input tileset to the latest version"
    },
    {
      "name": "_b3dmToGlb",
      "description": "Convert B3DM to GLB",
      "contentStages": [
        {
          "name": "b3dmToGlb",
          "description": "Convert each B3DM content into GLB"
        }
      ]
    },
    {
      "name": "gzip",
      "description": "Compresses each entry with GZIP"
    }
  ]
}
```
you can also see screenshot of output data as well as terminal screenshot
<img width="796" alt="Screenshot 2023-06-29 at 10 53 49" src="https://github.com/CesiumGS/3d-tiles-tools/assets/16525701/ed9352e2-dacd-4916-be35-2a102a71aa01">
<img width="887" alt="Screenshot 2023-06-29 at 10 47 19" src="https://github.com/CesiumGS/3d-tiles-tools/assets/16525701/54569d71-04bd-4dfe-bba8-d5aadeb6f519">

**Comment by javagl** [comment] 2023-06-29 12:58
Only from a **quick** look:

With 
`npx 3d-tiles-tools ...` 
you're probably starting the _installed_ version (which is the one without #42 ).
(I'll have to look up some details of `npx` to be sure here, but I think that this is what happens)

When you cloned the latest state from the repo, and are in the root directory of the cloned repo, the call should be
`npx ts-node ./src/main.ts ...`
to actually run it with the source code of the cloned state.

So your call would be
`npx ts-node ./src/main.ts pipeline -i /media/pip/6TB_1/data/old/3d/z.json`

If this does not fix the issue, I'll have another look and try it out again locally.

(And... we should definitely schedule a new release of the latest state, but ... there are many things of which it would be desirable to make them part of that next release, so we'll have to think about the best schedule here...)

**Comment by vkitor** [comment] 2023-06-30 08:30
Thank you for the suggestion.

I tried explicitly calling the` ./src/main.ts pipeline` as you said, but the result was same.

Would it help if I shared my dataset with you?

**Comment by javagl** [comment] 2023-06-30 10:58
> Would it help if I shared my dataset with you?

If it is not unreasonably large, that could indeed help.

I just tried it out with one of the "test" tilesets of which I think that it might be structurally similar to yours. The `./specs/data/Tileset` is a simple tileset that contains B3DM files (and refers to them with a `url`, this requiring the `upgrade` step). It can be processed with 
`npx ts-node ./src/main.ts pipeline -i pipeline.json`
using the followng `pipeline.json`
```
{
  "input": "./specs/data/Tileset/tileset.json",
  "output": "./output/result",
  "tilesetStages": [
    {
      "name": "upgrade",
      "description": "Upgrade the input tileset to the latest version"
    },
    {
      "name": "_b3dmToGlb",
      "description": "Convert B3DM to GLB",
      "contentStages": [
        {
          "name": "b3dmToGlb",
          "description": "Convert each B3DM content into GLB"
        }
      ]
    },
    {
      "name": "gzip",
      "description": "Compresses each entry with GZIP"
    }
  ]
}
```
And the result indeed is a tileset that refers to GLB files (all being zipped).

So I'm curious what could be the difference between this tileset and your tileset that may cause the different behavior here.

**Comment by vkitor** [comment] 2023-07-04 14:42
Hi,

I have prepared a small part of mesh for you to try. you can find it on link: https://drive.google.com/file/d/1y9rsiiDcBrRBmRPiRV6XhkuHi5HiCpVe/view?usp=sharing 

These are my settings and results:

`npx ts-node ./src/main.ts pipeline -i /media/pip/6TB_1/pipeline_test_ex/z.json `

z.json:
```

{
  "input": "/media/pip/6TB_1/pipeline_test_ex/Draco_compressed/cs_conversion_example/tileset.json",
  "output": "/media/pip/6TB_1/pipeline_test_ex/Draco_compressed/pipeline_export/",
  "tilesetStages": [
    {
      "name": "upgrade",
      "description": "Upgrade the input tileset to the latest version"
    },
    {
      "name": "_b3dmToGlb",
      "description": "Convert B3DM to GLB",
      "contentStages": [
        {
          "name": "b3dmToGlb",
          "description": "Convert each B3DM content into GLB"
        }
      ]
    },
    {
      "name": "gzip",
      "description": "Compresses each entry with GZIP"
    }
  ]
}
```
<img width="893" alt="Screenshot 2023-07-04 at 16 35 52" src="https://github.com/CesiumGS/3d-tiles-tools/assets/16525701/97d03b1d-e0f7-4018-9c85-0e7e4fc625f6">
<img width="636" alt="Screenshot 2023-07-04 at 16 35 29" src="https://github.com/CesiumGS/3d-tiles-tools/assets/16525701/320530ac-aedb-431a-92ba-9c99c83364f0">

**Comment by javagl** [comment] 2023-07-04 17:42
Thanks for that example. I have identified the problem: The content processing does not properly handle the case where the contents of external tilesets are in subdirectories. (This _should_ have been an obvious case to test, but wasn't covered with the `specs` data that I initially created). 

Fixing this will require some tweaking and tests, involving some more complex test cases. For example:

- `tileset.json` refers to 
  - `ExternalA/externalA.json`
  - `ExternalB/externalB.json`

- `ExternalA/externalA.json` refers to
  - `tileA.b3dm` (in the `ExternalA` subdirectory) and
  - `../tileX.b3dm` (in the root directory)

- `ExternalB/externalB.json` refers to
  - `tileB.b3dm` (in the `ExternalB` subdirectory) and
  - **also** to `../tileX.b3dm` (in the root directory)

On the one hand, this _looks_ simple: Just keep track of the 'current base directory'. But with caveats, e.g. that the `tileX.b3dm` should only be touched _once_, and the `content.uri` inside each tileset JSONs will have to be updated properly.

I'll tackle this ASAP and drop a note here when it's done.

**Comment by javagl** [comment] 2023-07-05 20:27
A PR where the `RTC_CENTER` is applied to the resulting GLBs is at https://github.com/CesiumGS/3d-tiles-tools/pull/49 

There are some detail questions to be answered, but I tried it out with the tileset that you provided, and could render the resulting tileset in CesiumJS. Maybe you also want to give it a try and say whether it works as intended for you as well.

**Comment by vkitor** [comment] 2023-07-14 10:09
@javagl conversion works now. thank you.

Only problem I have now is that cesium js viewer is not showing glb tiles

**Comment by javagl** [comment] 2023-07-14 14:24
@vkitor It should defintely display them.

When using the state from https://github.com/CesiumGS/3d-tiles-tools/pull/49 and applying the pipeline
```
{
  "input": "D:/cs_conversion_example/tileset.json",
  "output": "D:/cs_conversion_example-OUTPUT/tileset.json",
  "tilesetStages": [
    {
      "name": "upgrade",
      "description": "Upgrade the input tileset to the latest version"
    },
    {
      "name": "_b3dmToGlb",
      "description": "Convert B3DM to GLB",
      "contentStages": [
        {
          "name": "b3dmToGlb",
          "description": "Convert each B3DM content into GLB"
        }
      ]
    }
  ]
}
```
and then serving the resulting directory into a sandcastle like this
```
const viewer = new Cesium.Viewer("cesiumContainer");

try {
  const tileset = await Cesium.Cesium3DTileset.fromUrl(
    "http://localhost:8003/tileset.json");
  viewer.scene.primitives.add(tileset);
  viewer.zoomTo(tileset);
} catch (error) {
  console.log(`Error loading tileset: ${error}`);
} 
```

Then the result for me is

![Cesium tools issue 46 screenshot](https://github.com/CesiumGS/3d-tiles-tools/assets/5597569/e526720e-06ac-4233-b73d-9729b74aefaf)

showing the tileset at the right place, and (as shown in the network tab) is indeed using the GLB tiles.

Do you see any differences in the process or the result that may cause it to not work for you?

**Comment by jo-chemla** [comment] 2023-07-21 17:10
Really useful conversation, thanks for these insights! The PR https://github.com/CesiumGS/3d-tiles-tools/pull/49 has been closed non-merged with the statement that `b3dmToGlb` should only **extract** mesh content from the glb payload, and applying `RTC_CENTER` to have correct tile-to-tile matrix-transforms would be part of the upgrade command - or a `convertB3dmToGlb` command. 

I'm also interested in second portion of the OP related to merging tiles of a tileset - to recover a mesh close to the original 3D data at the finest level of detail. I understand this is not yet covered by 3D-tiles-tools - and might as well never be part of that toolbelt. Has anyone already stumbled on a tool doing this or aiming at doing this at some point? 
Would be great to take all finest details leaf nodes (with REPLACE mode) from a tileset and merge together. 

For context, since we do store our datasets as 3D-tiles (for massive meshes, and COPC/Potree for massive pointclouds), recovering original mesh data (and eventually clipping with footprint/bbox) the way we can do it with COPC and pdal is important to manage massive reality scan data and easen workflows between different softwares from our team and client.

**Comment by javagl** [comment] 2023-07-21 19:01
> The PR https://github.com/CesiumGS/3d-tiles-tools/pull/49 has been closed non-merged with the statement that b3dmToGlb should only extract mesh content from the glb payload, and applying RTC_CENTER to have correct tile-to-tile matrix-transforms would be part of the upgrade command - or a convertB3dmToGlb command.

Yes. The _specific_ state in this PR did include the `RTC_CENTER`. But there should also be an way to _only_ extracts the GLB data. This could be solved with options, like that `-applyRtc=false` or so, but ... separating these tasks seemed like the cleanest solution here.

> I'm also interested in second portion of the OP related to merging tiles of a tileset - to recover a mesh close to the original 3D data at the finest level of detail. I understand this is not yet covered by 3D-tiles-tools - and might as well never be part of that toolbelt. Has anyone already stumbled on a tool doing this or aiming at doing this at some point?
> Would be great to take all finest details leaf nodes (with REPLACE mode) from a tileset and merge together.

There are many possible forms of post-processing that could be done on tilesets. As described above, extracting "all glTFs" at a certain level of detail would be simple. Applying possible translations to these glTFs would also be doable. Combining multiple glTFs into one might be possible, with some assumptions about the _structure_ of these glTFs. But eventually, this would be "the opposite" of what 3D Tiles is meant for (namely, streaming huge datasets with LOD). So while it could be possible to extract this data, it's important to have a clear idea about the requirements, intended behavior, and the goals. For example: Extracting a single GLB from a large 3D Tiles data set may quickly hit the inherent file size limit of GLB (which is 4GB, and most tools will not be able to process more than 2GB...).

**Comment by javagl** [comment] 2023-07-26 19:38
> ... we often produce 3D meshes/pointclouds of a few 10s of GB (500M - 15B datasets), so these would indeed be probably split into a few chunks (or exported to a file format other than glTF/glb).

Like... 3D Tiles, which can refer to smaller parts of the point cloud, as individual GLB files :-) 

Extracting a certain level of detail from a 3D Tiles data set is certainly something that could be considered. But it has some caveats. I might give it a try, just to explore some possible approaches (and if it works, maybe create a draft PR for it). But it's not a feature that we could promise to be readily available on a short-term roadmap.

**Comment by javagl** [comment] 2023-07-30 12:34
@vkitor 

> Only problem I have now is that cesium js viewer is not showing glb tiles

Has this been resolved, or can you provide details about possible error messages or so? I'm mainly wondering whether this issue can be closed (even though I'd still consider extracting the "Feature Request" to extract/merge GLBs in a dedicated issue, just to keep track of that and see what the demands and use-cases could be...)

**Comment by jo-chemla** [comment] 2023-07-31 08:39
> Like... 3D Tiles, which can refer to smaller parts of the point cloud, as individual GLB files :-)

Yes of course, what I had in mind is a way to ingest, for softwares which do not support it yet (AutoCAD, Blender etc), data that are 3D-tiles tilesets, so dealing with say 10 4GB glb meshes (~discrete lod) rather than 1000 tiles is what I'm after. Thanks for looking into it, and please do tell me if you want me to open a dedicated issue for that request, plus if you need any help!

**Comment by vkitor** [comment] 2023-08-08 10:07
@javagl 

I'm still struggling to replicate your results.

I tried using http-server as per [instructions](https://github.com/javagl/3d-tiles-samples/blob/198bab607f10f7d5583361a464f2e8cac149c8e7/INSTRUCTIONS.md) but had no succes.

I can get the viewer to show b3dm tiles, but not glb. As you can see in networking tab, browser gets glb but it is not showing.
<img width="3008" alt="Screenshot 2023-08-08 at 11 56 59" src="https://github.com/CesiumGS/3d-tiles-tools/assets/16525701/77047323-6cc4-4626-96e9-828ba1cda3a0">

<img width="3005" alt="Screenshot 2023-08-08 at 12 03 59" src="https://github.com/CesiumGS/3d-tiles-tools/assets/16525701/a1543f00-9562-4f91-90e4-2d0e03aac3b9">

processing .json:
```
{
  "input": "/.../3d_example/raw/",
  "output": ".../3d_example/glb/",
  "tilesetStages": [
    {
      "name": "upgrade",
      "description": "Upgrade the input tileset to the latest version"
    },
    {
      "name": "_b3dmToGlb",
      "description": "Convert B3DM to GLB",
      "contentStages": [
        {
          "name": "b3dmToGlb",
          "description": "Convert each B3DM content into GLB"
        }
      ]
    }
  ]
}
```

this is my viewer html:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <script src="https://cesium.com/downloads/cesiumjs/releases/1.107.1/Build/Cesium/Cesium.js"></script>
  <link href="https://cesium.com/downloads/cesiumjs/releases/1.107.1/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
</head>
<body>
  <div id="cesiumContainer"></div>
  <script type="module">
    const viewer = new Cesium.Viewer("cesiumContainer");
try {
  const tileset = await Cesium.Cesium3DTileset.fromUrl(
    "http://localhost:8003/glb_nozip/tileset.json");
  viewer.scene.primitives.add(tileset);
  viewer.zoomTo(tileset);
} catch (error) {
  console.log(`Error loading tileset: ${error}`);
} 
  </script>
 </div>
</body>
</html>
```

**Comment by javagl** [comment] 2023-08-08 11:46
I just tried it out again, exactly as described, and it seems to work. 

What is _particularly_ confusing is that the browser says that it loads the GLB, but nothing is visible. If there was something wrong with the paths or bounding volumes or the actual file contents, it should either not load anything, or cause _some_ form of error message.

I'm not sure what could be wrong here, and don't have really good ideas about how to debug this. 

As a first shot: Could you provide a ZIP file with

- `tileset.json`
- `Data/Tile_4/Tile_4.json`
- `Data/Tile_4/Tile_4.glb`

of the result? Maybe I can find some difference between your files and my local files that could explain why CesiumJS does not display them. (Maybe sharing the _full_ output directory as a ZIP would be easier - that's up to you. But I hope that with the files mentioned above, I can at least try it out and maybe find an idea on how to proceed here...)

**Comment by vkitor** [comment] 2023-08-08 12:39
you can find all the files on this url: https://drive.google.com/drive/folders/1UwV-tfOPPovZeBKKlzo4dVLUvSjo_yuW?usp=drive_link

**Comment by javagl** [comment] 2023-08-08 13:58
Sorry for the back and forth here.

Some of the functionality that you asked about was not yet supported when this issue was opened. The approach of using a `pipeline.json` was an attempt to solve this, but the exact behavior of some of the pipeline functions (specifically, the `b3dmToGlb`) had not yet been decided upon. 

---

An aside: This was the reason for the _preliminary_ https://github.com/CesiumGS/3d-tiles-tools/pull/49 . This was _not_ merged, but contains further information about the decisions that eventually have been made here. And from a quick look at two of the GLB assets (once with my current output, and once with the `3d_example\glb_nozip` that you provided), it looks like the current issue is indeed caused by the RTC_CENTER not being taken into account:

![Cesium 3d-tiles-tools issue 46](https://github.com/CesiumGS/3d-tiles-tools/assets/5597569/2919257c-945a-456f-b22b-256eefdb2b8c)

(Notice the different bounding boxes of the tiles, and the different "generator"). 

We could now try to figure out which branch _exactly_ you used for the conversion but ... maybe this is not necessary any more, because all this should now be **much** easier:

---

One goal of the [upgrade generalization](https://github.com/CesiumGS/3d-tiles-tools/pull/41) that was merged recently was to _exactly_ support the case that you have been looking for - namely, upgrading a 1.0 tileset to 1.1, including the conversion of B3DM tile content to GLB.

When you use the **current** state of the `main` branch (which is [this one](https://github.com/CesiumGS/3d-tiles-tools/tree/66d841d779e2ab543c902d12be5057ea4cef1004) at the time of writing this), then you should be able to use the `upgrade` command as follows:

`npx ts-node ./src/main.ts upgrade --targetVersion 1.1 -i C:/cs_conversion_example/ -o C:/cs_conversion_example-UPGRADED/`

This should upgrade the tileset and tile contents, _including_ the conversion of the B3DM to GLB.

There are many caveats and corner cases for this "generalized, automated upgrade". But for the data set that you provided, it seems to work as expected. Maybe you want to give it a try.

**Comment by vkitor** [comment] 2023-08-09 09:18
@javagl It works now. Thank you very much!

**Comment by javagl** [comment] 2023-08-29 17:31
The process of converting many B3DM tile contents to GLB should be covered with the extended `upgrade` function. There may always be cases where a tileset contains obscure ("very unusual") data and the upgrade might _not_ yield the expected result. But this should be tracked in dedicated issues when it comes up. So I think that it is OK to close this one for now.

**Closed by javagl** 2023-08-29 17:31 UTC
